import 'package:fitness_habit_tracker/features/habits/models/habit_model.dart';

final List<HabitModel> dataList = [
  HabitModel(
    id: '123',
    title: 'Set Small Goals',
    icon: '🎯',
    colorValue: 0xFF2196F3,
    repeatDays: [],
    repeatType: RepeatType.daily,
    timeOfDayType: TimeOfDayType.morning,
    isCompleted: false,
    createdAt: DateTime.now(),
  ),
  HabitModel(
    id: '234',
    title: 'Work',
    icon: '💼',
    colorValue: 0xFF9C27B0,
    repeatDays: [],
    repeatType: RepeatType.weekly,
    createdAt: DateTime.now(),
    isCompleted: false,
    timeOfDayType: TimeOfDayType.morning,
  ),
  HabitModel(
    id: '567',
    title: 'Meditation',
    icon: '🧘‍♂️',
    colorValue: 0xFF2196F3,
    repeatDays: [],
    repeatType: RepeatType.daily,
    timeOfDayType: TimeOfDayType.evening,
    createdAt: DateTime.now(),
    isCompleted: false,
  ),
  HabitModel(
    id: '890',
    title: 'BasketBall',
    icon: '🏀',
    colorValue: 0xFF9C27B0,
    createdAt: DateTime.now(),
    repeatDays: [],
    repeatType: RepeatType.weekly,
    timeOfDayType: TimeOfDayType.afternoon,
    isCompleted: false,
  ),
  HabitModel(
    id: '345',
    title: 'Sleep Over 8hr',
    icon: '😴',
    colorValue: 0xFFFF9800,
    isCompleted: true,
    createdAt: DateTime.now(),
    repeatDays: [],
    repeatType: RepeatType.daily,
    timeOfDayType: TimeOfDayType.evening,
  ),
  HabitModel(
    id: '2341',
    title: 'Playing Games',
    icon: '🎮',
    colorValue: 0xFF2196F3,
    repeatDays: [],
    repeatType: RepeatType.weekly,
    timeOfDayType: TimeOfDayType.afternoon,
    isCompleted: true,
    createdAt: DateTime.now(),
  ),
  HabitModel(
    id: '345',
    title: 'Exercise',
    icon: '🥊',
    colorValue: 0xFFFF9800,
    repeatDays: [],
    repeatType: RepeatType.daily,
    timeOfDayType: TimeOfDayType.morning,
    isCompleted: true,
    createdAt: DateTime.now(),
  ),
];
